security:
  web:
    enabled: false
logging:
  level:
    root: INFO
    com.franchy.lil.demo: DEBUG
  file:
    name: logs/spring-boot-application-dev.log
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    web:
      enabled: false
  config:
    activate:
      on-profile: dev