name: Java 17 + Docker Compose CI

on:
  push:
    branches:
      - '**'         # Runs on any branch push (including new branches)
  pull_request:
    types:
      - closed       # Runs when a PR is closed (merged or not)
    branches:
      - master       # Only if the PR targets master

jobs:
  build-and-test:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run tests
        run: mvn test

      - name: Shut down services
        run: docker-compose down
